project_id = "ufksgrounhmfafdajbrr"

[functions.validate-share-token]
verify_jwt = false

[functions.create-share-token]
verify_jwt = false

[functions.google-sheets]
verify_jwt = false

[functions.google-auth]
enabled = true
verify_jwt = false

[functions.meta-auth]
enabled = true
verify_jwt = false

[functions.meta-api]
enabled = true
verify_jwt = false

[functions.payment-attribution]
enabled = true
verify_jwt = false
