// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_STORAGE_KEY = 'sb-hzstynttwwjlhvywemml-auth-token';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const sanitizeHeaderValue = (value: unknown) =>
  String(value).replace(/[^\x00-\xff]/g, '');

const normalizeHeaders = (headers?: HeadersInit) => {
  const normalized = new Headers();

  if (!headers) return normalized;

  if (headers instanceof Headers) {
    headers.forEach((value, name) => {
      normalized.set(name, sanitizeHeaderValue(value));
    });
    return normalized;
  }

  if (Array.isArray(headers)) {
    headers.forEach(([name, value]) => {
      normalized.append(name, sanitizeHeaderValue(value));
    });
    return normalized;
  }

  Object.entries(headers).forEach(([name, value]) => {
    if (value !== undefined) {
      normalized.set(name, sanitizeHeaderValue(value));
    }
  });

  return normalized;
};

const createAbortError = () => {
  if (typeof DOMException !== 'undefined') {
    return new DOMException('Tempo esgotado ao consultar o Supabase.', 'AbortError');
  }

  return new Error('Tempo esgotado ao consultar o Supabase.');
};

const supabaseFetch: typeof fetch = async (input, init = {}) => {
  const nativeFetch = globalThis.fetch.bind(globalThis);
  const timeoutController = new AbortController();
  const callerSignal = init.signal;
  const requestHeaders =
    init.headers ??
    (typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
  let callerAbortHandler: (() => void) | null = null;

  if (callerSignal?.aborted) {
    timeoutController.abort(callerSignal.reason);
  } else if (callerSignal) {
    callerAbortHandler = () => timeoutController.abort(callerSignal.reason);
    callerSignal.addEventListener('abort', callerAbortHandler, { once: true });
  }

  const timeoutId = globalThis.setTimeout(() => {
    timeoutController.abort(createAbortError());
  }, 15_000);

  try {
    const safeInit: RequestInit = {
      ...init,
      signal: timeoutController.signal,
    };

    if (requestHeaders) {
      safeInit.headers = normalizeHeaders(requestHeaders);
    }

    return await nativeFetch(input, safeInit);
  } finally {
    globalThis.clearTimeout(timeoutId);
    if (callerSignal && callerAbortHandler) {
      callerSignal.removeEventListener('abort', callerAbortHandler);
    }
  }
};

function installHeaderValueGuard() {
  if (typeof Headers === 'undefined') return;

  const headersPrototype = Headers.prototype as Headers & {
    __latin1GuardInstalled?: boolean;
  };

  if (headersPrototype.__latin1GuardInstalled) return;

  const originalSet = headersPrototype.set;
  const originalAppend = headersPrototype.append;

  headersPrototype.set = function guardedSet(name: string, value: string) {
    try {
      return originalSet.call(this, name, value);
    } catch (error) {
      if (error instanceof TypeError && String(error.message).includes('ISO-8859-1')) {
        return originalSet.call(this, name, sanitizeHeaderValue(value));
      }
      throw error;
    }
  };

  headersPrototype.append = function guardedAppend(name: string, value: string) {
    try {
      return originalAppend.call(this, name, value);
    } catch (error) {
      if (error instanceof TypeError && String(error.message).includes('ISO-8859-1')) {
        return originalAppend.call(this, name, sanitizeHeaderValue(value));
      }
      throw error;
    }
  };

  headersPrototype.__latin1GuardInstalled = true;
}

installHeaderValueGuard();

async function readStoredSession() {
  if (typeof window === 'undefined') return null;

  const rawSession = window.localStorage.getItem(SUPABASE_STORAGE_KEY);
  if (!rawSession) return null;

  try {
    const session = JSON.parse(rawSession);
    const expiresAt = Number(session?.expires_at || 0);
    const refreshToken = String(session?.refresh_token || '');

    if (expiresAt && expiresAt * 1000 - Date.now() > 60_000) {
      return session;
    }

    if (!refreshToken) {
      window.localStorage.removeItem(SUPABASE_STORAGE_KEY);
      return null;
    }

    const response = await supabaseFetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`, {
      method: 'POST',
      headers: {
        apikey: SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ refresh_token: refreshToken }),
    });

    const refreshed = await response.json();
    if (!response.ok || !refreshed?.access_token) {
      window.localStorage.removeItem(SUPABASE_STORAGE_KEY);
      return null;
    }

    const nextSession = {
      ...session,
      ...refreshed,
      refresh_token: refreshed.refresh_token || session.refresh_token,
      expires_at: refreshed.expires_at || Math.floor(Date.now() / 1000) + Number(refreshed.expires_in || 3600),
      user: refreshed.user || session.user,
    };

    window.localStorage.setItem(SUPABASE_STORAGE_KEY, JSON.stringify(nextSession));
    return nextSession;
  } catch {
    window.localStorage.removeItem(SUPABASE_STORAGE_KEY);
    return null;
  }
}

const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseFetch,
    // Force ASCII-only client metadata headers so the SDK can still build its
    // internal Headers object on Windows/Brave without tripping over invalid
    // platform version strings.
    headers: {
      'X-Client-Info': 'supabase-js-web/2.93.1',
      'X-Supabase-Client-Platform': 'web',
      'X-Supabase-Client-Platform-Version': '0',
      'X-Supabase-Client-Runtime': 'browser',
      'X-Supabase-Client-Runtime-Version': '0',
    },
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'implicit',
    lock: async (_name, _acquireTimeout, fn) => fn(),
  }
});

supabaseClient.auth.getSession = async () => {
  const session = await readStoredSession();
  return { data: { session }, error: null };
};

export const supabase = supabaseClient;
